# Generated by Django 4.1.7 on 2023-04-04 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0005_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
