# Generated by Django 4.1.7 on 2023-04-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0007_alter_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('time_of_day', models.TimeField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.teacher')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
