# Generated by Django 4.1.7 on 2023-04-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0009_alter_timetable_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.CharField(choices=[('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('01:00 PM - 02:00 PM', '01:00 PM - 02:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM')], default='', max_length=20),
        ),
    ]
