# Generated by Django 4.1.7 on 2023-03-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentleave',
            table='studentleave',
        ),
    ]
