# Generated by Django 4.1.7 on 2023-03-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0004_remove_studentleave_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleave',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentleave',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='student_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
