# Generated by Django 4.1.7 on 2023-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentleave_student_id_studentleave_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleave',
            name='student_code',
        ),
        migrations.AddField(
            model_name='studentleave',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
